---
- hosts: all
  tasks:
    - name: Testing andrewrothstein.xet
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing '/usr/local/bin/git-xet --version'
      ansible.builtin.command: /usr/local/bin/git-xet --version
      register: xet_test_output
    - name: Output from '/usr/local/bin/git-xet --version'
      ansible.builtin.debug:
        msg: '{{ xet_test_output.stdout }}'
